import type { Metadata } from "next";
import { Inter } from "next/font/google";
import '../styles/globals.css';
import NavBar from '@/app/components/common/navBar';  // Adjust the path as necessary

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shelfie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-white`}>
        <NavBar /> {/* NavBar will appear on every page */}
        {children}
      </body>
    </html>
  );
}
